services:
  - type: web
    name: certificate-verification-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --production=false
      npx tailwindcss -i ./input.css -o ./static/output.css --minify || echo "Tailwind build failed, continuing..."
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 